/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdId = bigint;
export interface AdPublic {
  'id' : AdId,
  'durationDays' : bigint,
  'endDate' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'totalCost' : bigint,
  'targetUrl' : string,
  'isActive' : boolean,
  'logoUrl' : string,
  'slotType' : AdSlotType,
  'advertiserId' : UserId,
  'startDate' : Timestamp,
}
export interface AdPurchaseRequest {
  'durationDays' : bigint,
  'name' : string,
  'targetUrl' : string,
  'logoUrl' : string,
  'slotType' : AdSlotType,
}
export type AdSlotType = { 'homepage_banner' : null } |
  { 'sidebar' : null } |
  { 'pre_roll' : null };
export type CommentId = bigint;
export interface CommentPublic {
  'id' : CommentId,
  'isDeleted' : boolean,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'authorName' : string,
  'videoId' : VideoId,
}
export interface CreatorEarningsPublic {
  'videoEarnings' : Array<[VideoId, bigint]>,
  'creatorId' : UserId,
  'totalEarnings' : bigint,
}
export interface CreatorPayout {
  'creatorId' : UserId,
  'timestamp' : Timestamp,
  'amount' : bigint,
  'videoId' : [] | [VideoId],
}
export type LiveStreamId = bigint;
export interface LiveStreamPublic {
  'id' : LiveStreamId,
  'status' : LiveStreamStatus,
  'title' : string,
  'startedAt' : [] | [Timestamp],
  'endedAt' : [] | [Timestamp],
  'creatorId' : UserId,
  'description' : string,
  'creatorName' : string,
  'archivedVideoId' : [] | [VideoId],
  'viewerCount' : bigint,
  'scheduledAt' : Timestamp,
}
export type LiveStreamStatus = { 'scheduled' : null } |
  { 'active' : null } |
  { 'ended' : null } |
  { 'archived' : null };
export interface Page {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<VideoPublic>,
}
export interface PlatformStats {
  'totalAdRevenue' : bigint,
  'totalRewardsPaid' : bigint,
  'totalViewers' : bigint,
  'totalCreators' : bigint,
  'totalAdmins' : bigint,
  'platformBalance' : bigint,
  'totalCreatorPayouts' : bigint,
  'totalAdvertisers' : bigint,
  'totalVideos' : bigint,
}
export interface PostCommentRequest { 'text' : string, 'videoId' : VideoId }
export interface RegisterRequest {
  'username' : string,
  'role' : UserRole,
  'email' : string,
}
export interface RewardSummary {
  'pendingReward' : bigint,
  'dailyWatchSeconds' : bigint,
  'balance' : bigint,
  'totalEarned' : bigint,
}
export interface StartLiveStreamRequest {
  'title' : string,
  'description' : string,
  'scheduledAt' : Timestamp,
}
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'username' : [] | [string],
  'email' : [] | [string],
}
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'status' : UserStatus,
  'username' : string,
  'balance' : bigint,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'creator' : null } |
  { 'admin' : null } |
  { 'advertiser' : null } |
  { 'viewer' : null };
export type UserStatus = { 'active' : null } |
  { 'suspended' : null } |
  { 'flagged' : null };
export type VideoId = bigint;
export interface VideoPublic {
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'creatorId' : UserId,
  'description' : string,
  'viewCount' : bigint,
  'totalWatchSeconds' : bigint,
  'category' : string,
  'videoUrl' : string,
}
export type VideoStatus = { 'published' : null } |
  { 'unpublished' : null } |
  { 'flagged' : null } |
  { 'draft' : null };
export interface VideoUploadRequest {
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : string,
  'videoUrl' : string,
}
export interface ViewerRewardPayout {
  'viewerId' : UserId,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export interface WatchEvent { 'watchSeconds' : bigint, 'videoId' : VideoId }
export interface _SERVICE {
  'approveUser' : ActorMethod<[UserId], undefined>,
  'archiveLiveStream' : ActorMethod<
    [LiveStreamId, string],
    { 'ok' : LiveStreamPublic } |
      { 'err' : string }
  >,
  'claimDailyReward' : ActorMethod<[], bigint>,
  'deleteComment' : ActorMethod<
    [CommentId, VideoId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'endLiveStream' : ActorMethod<
    [LiveStreamId],
    { 'ok' : LiveStreamPublic } |
      { 'err' : string }
  >,
  'flagUser' : ActorMethod<[UserId], undefined>,
  'flagVideo' : ActorMethod<[VideoId], undefined>,
  'getActiveAds' : ActorMethod<[AdSlotType], Array<AdPublic>>,
  'getAdSlotPricing' : ActorMethod<[], Array<[AdSlotType, bigint]>>,
  'getCreatorEarnings' : ActorMethod<[UserId], [] | [CreatorEarningsPublic]>,
  'getLikeCount' : ActorMethod<[VideoId], bigint>,
  'getLiveStream' : ActorMethod<[LiveStreamId], [] | [LiveStreamPublic]>,
  'getMyAdCampaigns' : ActorMethod<[], Array<AdPublic>>,
  'getMyCreatorEarnings' : ActorMethod<[], [] | [CreatorEarningsPublic]>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getMyRewardSummary' : ActorMethod<[], RewardSummary>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getRecommendedVideos' : ActorMethod<[bigint], Array<VideoPublic>>,
  'getRelatedVideos' : ActorMethod<[VideoId, bigint], Array<VideoPublic>>,
  'getTrendingVideos' : ActorMethod<[bigint], Array<VideoPublic>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getVideo' : ActorMethod<[VideoId], [] | [VideoPublic]>,
  'goLive' : ActorMethod<
    [LiveStreamId],
    { 'ok' : LiveStreamPublic } |
      { 'err' : string }
  >,
  'hasLiked' : ActorMethod<[VideoId], boolean>,
  'joinLiveStream' : ActorMethod<
    [LiveStreamId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'leaveLiveStream' : ActorMethod<
    [LiveStreamId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'listActiveLiveStreams' : ActorMethod<[], Array<LiveStreamPublic>>,
  'listAllCreatorPayouts' : ActorMethod<[], Array<CreatorPayout>>,
  'listAllViewerRewardPayouts' : ActorMethod<[], Array<ViewerRewardPayout>>,
  'listComments' : ActorMethod<[VideoId], Array<CommentPublic>>,
  'listPublishedVideos' : ActorMethod<[bigint, bigint], Page>,
  'listVideosByCreator' : ActorMethod<[UserId], Array<VideoPublic>>,
  'postComment' : ActorMethod<
    [PostCommentRequest],
    { 'ok' : CommentPublic } |
      { 'err' : string }
  >,
  'publishVideo' : ActorMethod<[VideoId], VideoPublic>,
  'purchaseAdSlot' : ActorMethod<[AdPurchaseRequest], AdPublic>,
  'recordWatchTime' : ActorMethod<[WatchEvent], undefined>,
  'register' : ActorMethod<[RegisterRequest], UserPublic>,
  'searchVideos' : ActorMethod<[string], Array<VideoPublic>>,
  'setAdSlotPricing' : ActorMethod<[AdSlotType, bigint], undefined>,
  'setCreatorRevenueSharePercent' : ActorMethod<[bigint], undefined>,
  'setViewerRewardPercent' : ActorMethod<[bigint], undefined>,
  'startLiveStream' : ActorMethod<
    [StartLiveStreamRequest],
    { 'ok' : LiveStreamPublic } |
      { 'err' : string }
  >,
  'toggleLike' : ActorMethod<[VideoId], boolean>,
  'unpublishVideo' : ActorMethod<[VideoId], VideoPublic>,
  'updateProfile' : ActorMethod<[UpdateProfileRequest], UserPublic>,
  'uploadVideo' : ActorMethod<[VideoUploadRequest], VideoPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];