/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const LiveStreamId = IDL.Nat;
export const LiveStreamStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'active' : IDL.Null,
  'ended' : IDL.Null,
  'archived' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const VideoId = IDL.Nat;
export const LiveStreamPublic = IDL.Record({
  'id' : LiveStreamId,
  'status' : LiveStreamStatus,
  'title' : IDL.Text,
  'startedAt' : IDL.Opt(Timestamp),
  'endedAt' : IDL.Opt(Timestamp),
  'creatorId' : UserId,
  'description' : IDL.Text,
  'creatorName' : IDL.Text,
  'archivedVideoId' : IDL.Opt(VideoId),
  'viewerCount' : IDL.Nat,
  'scheduledAt' : Timestamp,
});
export const CommentId = IDL.Nat;
export const AdSlotType = IDL.Variant({
  'homepage_banner' : IDL.Null,
  'sidebar' : IDL.Null,
  'pre_roll' : IDL.Null,
});
export const AdId = IDL.Nat;
export const AdPublic = IDL.Record({
  'id' : AdId,
  'durationDays' : IDL.Nat,
  'endDate' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'totalCost' : IDL.Nat,
  'targetUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Text,
  'slotType' : AdSlotType,
  'advertiserId' : UserId,
  'startDate' : Timestamp,
});
export const CreatorEarningsPublic = IDL.Record({
  'videoEarnings' : IDL.Vec(IDL.Tuple(VideoId, IDL.Nat)),
  'creatorId' : UserId,
  'totalEarnings' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
  'flagged' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'creator' : IDL.Null,
  'admin' : IDL.Null,
  'advertiser' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const RewardSummary = IDL.Record({
  'pendingReward' : IDL.Nat,
  'dailyWatchSeconds' : IDL.Nat,
  'balance' : IDL.Nat,
  'totalEarned' : IDL.Nat,
});
export const PlatformStats = IDL.Record({
  'totalAdRevenue' : IDL.Nat,
  'totalRewardsPaid' : IDL.Nat,
  'totalViewers' : IDL.Nat,
  'totalCreators' : IDL.Nat,
  'totalAdmins' : IDL.Nat,
  'platformBalance' : IDL.Nat,
  'totalCreatorPayouts' : IDL.Nat,
  'totalAdvertisers' : IDL.Nat,
  'totalVideos' : IDL.Nat,
});
export const VideoStatus = IDL.Variant({
  'published' : IDL.Null,
  'unpublished' : IDL.Null,
  'flagged' : IDL.Null,
  'draft' : IDL.Null,
});
export const VideoPublic = IDL.Record({
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'creatorId' : UserId,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'totalWatchSeconds' : IDL.Nat,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const CreatorPayout = IDL.Record({
  'creatorId' : UserId,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
  'videoId' : IDL.Opt(VideoId),
});
export const ViewerRewardPayout = IDL.Record({
  'viewerId' : UserId,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const CommentPublic = IDL.Record({
  'id' : CommentId,
  'isDeleted' : IDL.Bool,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'videoId' : VideoId,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(VideoPublic),
});
export const PostCommentRequest = IDL.Record({
  'text' : IDL.Text,
  'videoId' : VideoId,
});
export const AdPurchaseRequest = IDL.Record({
  'durationDays' : IDL.Nat,
  'name' : IDL.Text,
  'targetUrl' : IDL.Text,
  'logoUrl' : IDL.Text,
  'slotType' : AdSlotType,
});
export const WatchEvent = IDL.Record({
  'watchSeconds' : IDL.Nat,
  'videoId' : VideoId,
});
export const RegisterRequest = IDL.Record({
  'username' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const StartLiveStreamRequest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'scheduledAt' : Timestamp,
});
export const UpdateProfileRequest = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});
export const VideoUploadRequest = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'approveUser' : IDL.Func([UserId], [], []),
  'archiveLiveStream' : IDL.Func(
      [LiveStreamId, IDL.Text],
      [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
      [],
    ),
  'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
  'deleteComment' : IDL.Func(
      [CommentId, VideoId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'endLiveStream' : IDL.Func(
      [LiveStreamId],
      [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
      [],
    ),
  'flagUser' : IDL.Func([UserId], [], []),
  'flagVideo' : IDL.Func([VideoId], [], []),
  'getActiveAds' : IDL.Func([AdSlotType], [IDL.Vec(AdPublic)], ['query']),
  'getAdSlotPricing' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AdSlotType, IDL.Nat))],
      ['query'],
    ),
  'getCreatorEarnings' : IDL.Func(
      [UserId],
      [IDL.Opt(CreatorEarningsPublic)],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
  'getLiveStream' : IDL.Func(
      [LiveStreamId],
      [IDL.Opt(LiveStreamPublic)],
      ['query'],
    ),
  'getMyAdCampaigns' : IDL.Func([], [IDL.Vec(AdPublic)], ['query']),
  'getMyCreatorEarnings' : IDL.Func(
      [],
      [IDL.Opt(CreatorEarningsPublic)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getMyRewardSummary' : IDL.Func([], [RewardSummary], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], []),
  'getRecommendedVideos' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(VideoPublic)],
      ['query'],
    ),
  'getRelatedVideos' : IDL.Func(
      [VideoId, IDL.Nat],
      [IDL.Vec(VideoPublic)],
      ['query'],
    ),
  'getTrendingVideos' : IDL.Func([IDL.Nat], [IDL.Vec(VideoPublic)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoPublic)], ['query']),
  'goLive' : IDL.Func(
      [LiveStreamId],
      [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
      [],
    ),
  'hasLiked' : IDL.Func([VideoId], [IDL.Bool], ['query']),
  'joinLiveStream' : IDL.Func(
      [LiveStreamId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'leaveLiveStream' : IDL.Func(
      [LiveStreamId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'listActiveLiveStreams' : IDL.Func(
      [],
      [IDL.Vec(LiveStreamPublic)],
      ['query'],
    ),
  'listAllCreatorPayouts' : IDL.Func([], [IDL.Vec(CreatorPayout)], []),
  'listAllViewerRewardPayouts' : IDL.Func(
      [],
      [IDL.Vec(ViewerRewardPayout)],
      [],
    ),
  'listComments' : IDL.Func([VideoId], [IDL.Vec(CommentPublic)], ['query']),
  'listPublishedVideos' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'listVideosByCreator' : IDL.Func([UserId], [IDL.Vec(VideoPublic)], ['query']),
  'postComment' : IDL.Func(
      [PostCommentRequest],
      [IDL.Variant({ 'ok' : CommentPublic, 'err' : IDL.Text })],
      [],
    ),
  'publishVideo' : IDL.Func([VideoId], [VideoPublic], []),
  'purchaseAdSlot' : IDL.Func([AdPurchaseRequest], [AdPublic], []),
  'recordWatchTime' : IDL.Func([WatchEvent], [], []),
  'register' : IDL.Func([RegisterRequest], [UserPublic], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoPublic)], ['query']),
  'setAdSlotPricing' : IDL.Func([AdSlotType, IDL.Nat], [], []),
  'setCreatorRevenueSharePercent' : IDL.Func([IDL.Nat], [], []),
  'setViewerRewardPercent' : IDL.Func([IDL.Nat], [], []),
  'startLiveStream' : IDL.Func(
      [StartLiveStreamRequest],
      [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
      [],
    ),
  'toggleLike' : IDL.Func([VideoId], [IDL.Bool], []),
  'unpublishVideo' : IDL.Func([VideoId], [VideoPublic], []),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [UserPublic], []),
  'uploadVideo' : IDL.Func([VideoUploadRequest], [VideoPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const LiveStreamId = IDL.Nat;
  const LiveStreamStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'active' : IDL.Null,
    'ended' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const VideoId = IDL.Nat;
  const LiveStreamPublic = IDL.Record({
    'id' : LiveStreamId,
    'status' : LiveStreamStatus,
    'title' : IDL.Text,
    'startedAt' : IDL.Opt(Timestamp),
    'endedAt' : IDL.Opt(Timestamp),
    'creatorId' : UserId,
    'description' : IDL.Text,
    'creatorName' : IDL.Text,
    'archivedVideoId' : IDL.Opt(VideoId),
    'viewerCount' : IDL.Nat,
    'scheduledAt' : Timestamp,
  });
  const CommentId = IDL.Nat;
  const AdSlotType = IDL.Variant({
    'homepage_banner' : IDL.Null,
    'sidebar' : IDL.Null,
    'pre_roll' : IDL.Null,
  });
  const AdId = IDL.Nat;
  const AdPublic = IDL.Record({
    'id' : AdId,
    'durationDays' : IDL.Nat,
    'endDate' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'totalCost' : IDL.Nat,
    'targetUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Text,
    'slotType' : AdSlotType,
    'advertiserId' : UserId,
    'startDate' : Timestamp,
  });
  const CreatorEarningsPublic = IDL.Record({
    'videoEarnings' : IDL.Vec(IDL.Tuple(VideoId, IDL.Nat)),
    'creatorId' : UserId,
    'totalEarnings' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'creator' : IDL.Null,
    'admin' : IDL.Null,
    'advertiser' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const RewardSummary = IDL.Record({
    'pendingReward' : IDL.Nat,
    'dailyWatchSeconds' : IDL.Nat,
    'balance' : IDL.Nat,
    'totalEarned' : IDL.Nat,
  });
  const PlatformStats = IDL.Record({
    'totalAdRevenue' : IDL.Nat,
    'totalRewardsPaid' : IDL.Nat,
    'totalViewers' : IDL.Nat,
    'totalCreators' : IDL.Nat,
    'totalAdmins' : IDL.Nat,
    'platformBalance' : IDL.Nat,
    'totalCreatorPayouts' : IDL.Nat,
    'totalAdvertisers' : IDL.Nat,
    'totalVideos' : IDL.Nat,
  });
  const VideoStatus = IDL.Variant({
    'published' : IDL.Null,
    'unpublished' : IDL.Null,
    'flagged' : IDL.Null,
    'draft' : IDL.Null,
  });
  const VideoPublic = IDL.Record({
    'id' : VideoId,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'creatorId' : UserId,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'totalWatchSeconds' : IDL.Nat,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const CreatorPayout = IDL.Record({
    'creatorId' : UserId,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
    'videoId' : IDL.Opt(VideoId),
  });
  const ViewerRewardPayout = IDL.Record({
    'viewerId' : UserId,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const CommentPublic = IDL.Record({
    'id' : CommentId,
    'isDeleted' : IDL.Bool,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'videoId' : VideoId,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(VideoPublic),
  });
  const PostCommentRequest = IDL.Record({
    'text' : IDL.Text,
    'videoId' : VideoId,
  });
  const AdPurchaseRequest = IDL.Record({
    'durationDays' : IDL.Nat,
    'name' : IDL.Text,
    'targetUrl' : IDL.Text,
    'logoUrl' : IDL.Text,
    'slotType' : AdSlotType,
  });
  const WatchEvent = IDL.Record({
    'watchSeconds' : IDL.Nat,
    'videoId' : VideoId,
  });
  const RegisterRequest = IDL.Record({
    'username' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const StartLiveStreamRequest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'scheduledAt' : Timestamp,
  });
  const UpdateProfileRequest = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  const VideoUploadRequest = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'approveUser' : IDL.Func([UserId], [], []),
    'archiveLiveStream' : IDL.Func(
        [LiveStreamId, IDL.Text],
        [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
        [],
      ),
    'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
    'deleteComment' : IDL.Func(
        [CommentId, VideoId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'endLiveStream' : IDL.Func(
        [LiveStreamId],
        [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
        [],
      ),
    'flagUser' : IDL.Func([UserId], [], []),
    'flagVideo' : IDL.Func([VideoId], [], []),
    'getActiveAds' : IDL.Func([AdSlotType], [IDL.Vec(AdPublic)], ['query']),
    'getAdSlotPricing' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AdSlotType, IDL.Nat))],
        ['query'],
      ),
    'getCreatorEarnings' : IDL.Func(
        [UserId],
        [IDL.Opt(CreatorEarningsPublic)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
    'getLiveStream' : IDL.Func(
        [LiveStreamId],
        [IDL.Opt(LiveStreamPublic)],
        ['query'],
      ),
    'getMyAdCampaigns' : IDL.Func([], [IDL.Vec(AdPublic)], ['query']),
    'getMyCreatorEarnings' : IDL.Func(
        [],
        [IDL.Opt(CreatorEarningsPublic)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getMyRewardSummary' : IDL.Func([], [RewardSummary], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], []),
    'getRecommendedVideos' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VideoPublic)],
        ['query'],
      ),
    'getRelatedVideos' : IDL.Func(
        [VideoId, IDL.Nat],
        [IDL.Vec(VideoPublic)],
        ['query'],
      ),
    'getTrendingVideos' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VideoPublic)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoPublic)], ['query']),
    'goLive' : IDL.Func(
        [LiveStreamId],
        [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
        [],
      ),
    'hasLiked' : IDL.Func([VideoId], [IDL.Bool], ['query']),
    'joinLiveStream' : IDL.Func(
        [LiveStreamId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'leaveLiveStream' : IDL.Func(
        [LiveStreamId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'listActiveLiveStreams' : IDL.Func(
        [],
        [IDL.Vec(LiveStreamPublic)],
        ['query'],
      ),
    'listAllCreatorPayouts' : IDL.Func([], [IDL.Vec(CreatorPayout)], []),
    'listAllViewerRewardPayouts' : IDL.Func(
        [],
        [IDL.Vec(ViewerRewardPayout)],
        [],
      ),
    'listComments' : IDL.Func([VideoId], [IDL.Vec(CommentPublic)], ['query']),
    'listPublishedVideos' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'listVideosByCreator' : IDL.Func(
        [UserId],
        [IDL.Vec(VideoPublic)],
        ['query'],
      ),
    'postComment' : IDL.Func(
        [PostCommentRequest],
        [IDL.Variant({ 'ok' : CommentPublic, 'err' : IDL.Text })],
        [],
      ),
    'publishVideo' : IDL.Func([VideoId], [VideoPublic], []),
    'purchaseAdSlot' : IDL.Func([AdPurchaseRequest], [AdPublic], []),
    'recordWatchTime' : IDL.Func([WatchEvent], [], []),
    'register' : IDL.Func([RegisterRequest], [UserPublic], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoPublic)], ['query']),
    'setAdSlotPricing' : IDL.Func([AdSlotType, IDL.Nat], [], []),
    'setCreatorRevenueSharePercent' : IDL.Func([IDL.Nat], [], []),
    'setViewerRewardPercent' : IDL.Func([IDL.Nat], [], []),
    'startLiveStream' : IDL.Func(
        [StartLiveStreamRequest],
        [IDL.Variant({ 'ok' : LiveStreamPublic, 'err' : IDL.Text })],
        [],
      ),
    'toggleLike' : IDL.Func([VideoId], [IDL.Bool], []),
    'unpublishVideo' : IDL.Func([VideoId], [VideoPublic], []),
    'updateProfile' : IDL.Func([UpdateProfileRequest], [UserPublic], []),
    'uploadVideo' : IDL.Func([VideoUploadRequest], [VideoPublic], []),
  });
};

export const init = ({ IDL }) => { return []; };