/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ViewerRewardPayout {
    viewerId: UserId;
    timestamp: Timestamp;
    amount: bigint;
}
export interface WatchEvent {
    watchSeconds: bigint;
    videoId: VideoId;
}
export interface UserPublic {
    id: UserId;
    status: UserStatus;
    username: string;
    balance: bigint;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface PostCommentRequest {
    text: string;
    videoId: VideoId;
}
export interface AdPurchaseRequest {
    durationDays: bigint;
    name: string;
    targetUrl: string;
    logoUrl: string;
    slotType: AdSlotType;
}
export interface AdPublic {
    id: AdId;
    durationDays: bigint;
    endDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    totalCost: bigint;
    targetUrl: string;
    isActive: boolean;
    logoUrl: string;
    slotType: AdSlotType;
    advertiserId: UserId;
    startDate: Timestamp;
}
export type LiveStreamId = bigint;
export interface UpdateProfileRequest {
    username?: string;
    email?: string;
}
export interface Page {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<VideoPublic>;
}
export interface VideoUploadRequest {
    title: string;
    thumbnailUrl: string;
    tags: Array<string>;
    description: string;
    category: string;
    videoUrl: string;
}
export interface VideoPublic {
    id: VideoId;
    status: VideoStatus;
    title: string;
    thumbnailUrl: string;
    createdAt: Timestamp;
    tags: Array<string>;
    creatorId: UserId;
    description: string;
    viewCount: bigint;
    totalWatchSeconds: bigint;
    category: string;
    videoUrl: string;
}
export type VideoId = bigint;
export interface RegisterRequest {
    username: string;
    role: UserRole;
    email: string;
}
export interface PlatformStats {
    totalAdRevenue: bigint;
    totalRewardsPaid: bigint;
    totalViewers: bigint;
    totalCreators: bigint;
    totalAdmins: bigint;
    platformBalance: bigint;
    totalCreatorPayouts: bigint;
    totalAdvertisers: bigint;
    totalVideos: bigint;
}
export type AdId = bigint;
export interface CreatorEarningsPublic {
    videoEarnings: Array<[VideoId, bigint]>;
    creatorId: UserId;
    totalEarnings: bigint;
}
export type CommentId = bigint;
export interface CreatorPayout {
    creatorId: UserId;
    timestamp: Timestamp;
    amount: bigint;
    videoId?: VideoId;
}
export interface CommentPublic {
    id: CommentId;
    isDeleted: boolean;
    authorId: UserId;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    videoId: VideoId;
}
export interface LiveStreamPublic {
    id: LiveStreamId;
    status: LiveStreamStatus;
    title: string;
    startedAt?: Timestamp;
    endedAt?: Timestamp;
    creatorId: UserId;
    description: string;
    creatorName: string;
    archivedVideoId?: VideoId;
    viewerCount: bigint;
    scheduledAt: Timestamp;
}
export type UserId = Principal;
export interface RewardSummary {
    pendingReward: bigint;
    dailyWatchSeconds: bigint;
    balance: bigint;
    totalEarned: bigint;
}
export interface StartLiveStreamRequest {
    title: string;
    description: string;
    scheduledAt: Timestamp;
}
export enum AdSlotType {
    homepage_banner = "homepage_banner",
    sidebar = "sidebar",
    pre_roll = "pre_roll"
}
export enum LiveStreamStatus {
    scheduled = "scheduled",
    active = "active",
    ended = "ended",
    archived = "archived"
}
export enum UserRole {
    creator = "creator",
    admin = "admin",
    advertiser = "advertiser",
    viewer = "viewer"
}
export enum UserStatus {
    active = "active",
    suspended = "suspended",
    flagged = "flagged"
}
export enum VideoStatus {
    published = "published",
    unpublished = "unpublished",
    flagged = "flagged",
    draft = "draft"
}
export interface backendInterface {
    approveUser(userId: UserId): Promise<void>;
    archiveLiveStream(streamId: LiveStreamId, videoUrl: string): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    claimDailyReward(): Promise<bigint>;
    deleteComment(commentId: CommentId, videoId: VideoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    endLiveStream(streamId: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    flagUser(userId: UserId): Promise<void>;
    flagVideo(videoId: VideoId): Promise<void>;
    getActiveAds(slotType: AdSlotType): Promise<Array<AdPublic>>;
    getAdSlotPricing(): Promise<Array<[AdSlotType, bigint]>>;
    getCreatorEarnings(creatorId: UserId): Promise<CreatorEarningsPublic | null>;
    getLikeCount(videoId: VideoId): Promise<bigint>;
    getLiveStream(id: LiveStreamId): Promise<LiveStreamPublic | null>;
    getMyAdCampaigns(): Promise<Array<AdPublic>>;
    getMyCreatorEarnings(): Promise<CreatorEarningsPublic | null>;
    getMyProfile(): Promise<UserPublic | null>;
    getMyRewardSummary(): Promise<RewardSummary>;
    getPlatformStats(): Promise<PlatformStats>;
    getRecommendedVideos(limit: bigint): Promise<Array<VideoPublic>>;
    getRelatedVideos(videoId: VideoId, limit: bigint): Promise<Array<VideoPublic>>;
    getTrendingVideos(limit: bigint): Promise<Array<VideoPublic>>;
    getUserProfile(userId: UserId): Promise<UserPublic | null>;
    getVideo(videoId: VideoId): Promise<VideoPublic | null>;
    goLive(streamId: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    hasLiked(videoId: VideoId): Promise<boolean>;
    joinLiveStream(id: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    leaveLiveStream(id: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listActiveLiveStreams(): Promise<Array<LiveStreamPublic>>;
    listAllCreatorPayouts(): Promise<Array<CreatorPayout>>;
    listAllViewerRewardPayouts(): Promise<Array<ViewerRewardPayout>>;
    listComments(videoId: VideoId): Promise<Array<CommentPublic>>;
    listPublishedVideos(offset: bigint, limit: bigint): Promise<Page>;
    listVideosByCreator(creatorId: UserId): Promise<Array<VideoPublic>>;
    postComment(req: PostCommentRequest): Promise<{
        __kind__: "ok";
        ok: CommentPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    publishVideo(videoId: VideoId): Promise<VideoPublic>;
    purchaseAdSlot(req: AdPurchaseRequest): Promise<AdPublic>;
    recordWatchTime(event: WatchEvent): Promise<void>;
    register(req: RegisterRequest): Promise<UserPublic>;
    searchVideos(term: string): Promise<Array<VideoPublic>>;
    setAdSlotPricing(slotType: AdSlotType, dailyPrice: bigint): Promise<void>;
    setCreatorRevenueSharePercent(percent: bigint): Promise<void>;
    setViewerRewardPercent(percent: bigint): Promise<void>;
    startLiveStream(req: StartLiveStreamRequest): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleLike(videoId: VideoId): Promise<boolean>;
    unpublishVideo(videoId: VideoId): Promise<VideoPublic>;
    updateProfile(req: UpdateProfileRequest): Promise<UserPublic>;
    uploadVideo(req: VideoUploadRequest): Promise<VideoPublic>;
}
import type { AdId as _AdId, AdPublic as _AdPublic, AdPurchaseRequest as _AdPurchaseRequest, AdSlotType as _AdSlotType, CommentPublic as _CommentPublic, CreatorEarningsPublic as _CreatorEarningsPublic, CreatorPayout as _CreatorPayout, LiveStreamId as _LiveStreamId, LiveStreamPublic as _LiveStreamPublic, LiveStreamStatus as _LiveStreamStatus, Page as _Page, RegisterRequest as _RegisterRequest, Timestamp as _Timestamp, UpdateProfileRequest as _UpdateProfileRequest, UserId as _UserId, UserPublic as _UserPublic, UserRole as _UserRole, UserStatus as _UserStatus, VideoId as _VideoId, VideoPublic as _VideoPublic, VideoStatus as _VideoStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async archiveLiveStream(arg0: LiveStreamId, arg1: string): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveLiveStream(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveLiveStream(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimDailyReward(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyReward();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyReward();
            return result;
        }
    }
    async deleteComment(arg0: CommentId, arg1: VideoId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async endLiveStream(arg0: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.endLiveStream(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endLiveStream(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async flagUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagUser(arg0);
            return result;
        }
    }
    async flagVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagVideo(arg0);
            return result;
        }
    }
    async getActiveAds(arg0: AdSlotType): Promise<Array<AdPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAds(to_candid_AdSlotType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAds(to_candid_AdSlotType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdSlotPricing(): Promise<Array<[AdSlotType, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdSlotPricing();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdSlotPricing();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorEarnings(arg0: UserId): Promise<CreatorEarningsPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorEarnings(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorEarnings(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikeCount(arg0: VideoId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount(arg0);
            return result;
        }
    }
    async getLiveStream(arg0: LiveStreamId): Promise<LiveStreamPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveStream(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveStream(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAdCampaigns(): Promise<Array<AdPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAdCampaigns();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAdCampaigns();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCreatorEarnings(): Promise<CreatorEarningsPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCreatorEarnings();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCreatorEarnings();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRewardSummary(): Promise<RewardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRewardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRewardSummary();
            return result;
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getRecommendedVideos(arg0: bigint): Promise<Array<VideoPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedVideos(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedVideos(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelatedVideos(arg0: VideoId, arg1: bigint): Promise<Array<VideoPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedVideos(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedVideos(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingVideos(arg0: bigint): Promise<Array<VideoPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingVideos(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingVideos(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<VideoPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async goLive(arg0: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.goLive(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.goLive(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasLiked(arg0: VideoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLiked(arg0);
            return result;
        }
    }
    async joinLiveStream(arg0: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinLiveStream(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinLiveStream(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveLiveStream(arg0: LiveStreamId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveLiveStream(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveLiveStream(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveLiveStreams(): Promise<Array<LiveStreamPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveLiveStreams();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveLiveStreams();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllCreatorPayouts(): Promise<Array<CreatorPayout>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCreatorPayouts();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCreatorPayouts();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllViewerRewardPayouts(): Promise<Array<ViewerRewardPayout>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllViewerRewardPayouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllViewerRewardPayouts();
            return result;
        }
    }
    async listComments(arg0: VideoId): Promise<Array<CommentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return result;
        }
    }
    async listPublishedVideos(arg0: bigint, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedVideos(arg0, arg1);
                return from_candid_Page_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedVideos(arg0, arg1);
            return from_candid_Page_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVideosByCreator(arg0: UserId): Promise<Array<VideoPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideosByCreator(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideosByCreator(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async postComment(arg0: PostCommentRequest): Promise<{
        __kind__: "ok";
        ok: CommentPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postComment(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postComment(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishVideo(arg0: VideoId): Promise<VideoPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.publishVideo(arg0);
                return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishVideo(arg0);
            return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseAdSlot(arg0: AdPurchaseRequest): Promise<AdPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseAdSlot(to_candid_AdPurchaseRequest_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseAdSlot(to_candid_AdPurchaseRequest_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordWatchTime(arg0: WatchEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWatchTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWatchTime(arg0);
            return result;
        }
    }
    async register(arg0: RegisterRequest): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterRequest_n42(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterRequest_n42(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdSlotPricing(arg0: AdSlotType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdSlotPricing(to_candid_AdSlotType_n9(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdSlotPricing(to_candid_AdSlotType_n9(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async setCreatorRevenueSharePercent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCreatorRevenueSharePercent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCreatorRevenueSharePercent(arg0);
            return result;
        }
    }
    async setViewerRewardPercent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setViewerRewardPercent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setViewerRewardPercent(arg0);
            return result;
        }
    }
    async startLiveStream(arg0: StartLiveStreamRequest): Promise<{
        __kind__: "ok";
        ok: LiveStreamPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startLiveStream(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startLiveStream(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleLike(arg0: VideoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async unpublishVideo(arg0: VideoId): Promise<VideoPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishVideo(arg0);
                return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishVideo(arg0);
            return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileRequest): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVideo(arg0: VideoUploadRequest): Promise<VideoPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0);
                return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0);
            return from_candid_VideoPublic_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdPublic): AdPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AdSlotType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdSlotType): AdSlotType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CreatorPayout_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorPayout): CreatorPayout {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_LiveStreamPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveStreamPublic): LiveStreamPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_LiveStreamStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveStreamStatus): LiveStreamStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_VideoPublic_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoPublic): VideoPublic {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CreatorEarningsPublic]): CreatorEarningsPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiveStreamPublic]): LiveStreamPublic | null {
    return value.length === 0 ? null : from_candid_LiveStreamPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoPublic]): VideoPublic | null {
    return value.length === 0 ? null : from_candid_VideoPublic_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoId]): VideoId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AdId;
    durationDays: bigint;
    endDate: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    totalCost: bigint;
    targetUrl: string;
    isActive: boolean;
    logoUrl: string;
    slotType: _AdSlotType;
    advertiserId: _UserId;
    startDate: _Timestamp;
}): {
    id: AdId;
    durationDays: bigint;
    endDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    totalCost: bigint;
    targetUrl: string;
    isActive: boolean;
    logoUrl: string;
    slotType: AdSlotType;
    advertiserId: UserId;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        endDate: value.endDate,
        name: value.name,
        createdAt: value.createdAt,
        totalCost: value.totalCost,
        targetUrl: value.targetUrl,
        isActive: value.isActive,
        logoUrl: value.logoUrl,
        slotType: from_candid_AdSlotType_n14(_uploadFile, _downloadFile, value.slotType),
        advertiserId: value.advertiserId,
        startDate: value.startDate
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    username: string;
    balance: bigint;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    id: UserId;
    status: UserStatus;
    username: string;
    balance: bigint;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n23(_uploadFile, _downloadFile, value.status),
        username: value.username,
        balance: value.balance,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n25(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    status: _VideoStatus;
    title: string;
    thumbnailUrl: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    creatorId: _UserId;
    description: string;
    viewCount: bigint;
    totalWatchSeconds: bigint;
    category: string;
    videoUrl: string;
}): {
    id: VideoId;
    status: VideoStatus;
    title: string;
    thumbnailUrl: string;
    createdAt: Timestamp;
    tags: Array<string>;
    creatorId: UserId;
    description: string;
    viewCount: bigint;
    totalWatchSeconds: bigint;
    category: string;
    videoUrl: string;
} {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n30(_uploadFile, _downloadFile, value.status),
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        createdAt: value.createdAt,
        tags: value.tags,
        creatorId: value.creatorId,
        description: value.description,
        viewCount: value.viewCount,
        totalWatchSeconds: value.totalWatchSeconds,
        category: value.category,
        videoUrl: value.videoUrl
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LiveStreamId;
    status: _LiveStreamStatus;
    title: string;
    startedAt: [] | [_Timestamp];
    endedAt: [] | [_Timestamp];
    creatorId: _UserId;
    description: string;
    creatorName: string;
    archivedVideoId: [] | [_VideoId];
    viewerCount: bigint;
    scheduledAt: _Timestamp;
}): {
    id: LiveStreamId;
    status: LiveStreamStatus;
    title: string;
    startedAt?: Timestamp;
    endedAt?: Timestamp;
    creatorId: UserId;
    description: string;
    creatorName: string;
    archivedVideoId?: VideoId;
    viewerCount: bigint;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_LiveStreamStatus_n4(_uploadFile, _downloadFile, value.status),
        title: value.title,
        startedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.startedAt)),
        endedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endedAt)),
        creatorId: value.creatorId,
        description: value.description,
        creatorName: value.creatorName,
        archivedVideoId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.archivedVideoId)),
        viewerCount: value.viewerCount,
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creatorId: _UserId;
    timestamp: _Timestamp;
    amount: bigint;
    videoId: [] | [_VideoId];
}): {
    creatorId: UserId;
    timestamp: Timestamp;
    amount: bigint;
    videoId?: VideoId;
} {
    return {
        creatorId: value.creatorId,
        timestamp: value.timestamp,
        amount: value.amount,
        videoId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.videoId))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_VideoPublic>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<VideoPublic>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n27(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AdSlotType, bigint]): [AdSlotType, bigint] {
    return [
        from_candid_AdSlotType_n14(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LiveStreamPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LiveStreamPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LiveStreamPublic_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    homepage_banner: null;
} | {
    sidebar: null;
} | {
    pre_roll: null;
}): AdSlotType {
    return "homepage_banner" in value ? AdSlotType.homepage_banner : "sidebar" in value ? AdSlotType.sidebar : "pre_roll" in value ? AdSlotType.pre_roll : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    suspended: null;
} | {
    flagged: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "suspended" in value ? UserStatus.suspended : "flagged" in value ? UserStatus.flagged : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: null;
} | {
    admin: null;
} | {
    advertiser: null;
} | {
    viewer: null;
}): UserRole {
    return "creator" in value ? UserRole.creator : "admin" in value ? UserRole.admin : "advertiser" in value ? UserRole.advertiser : "viewer" in value ? UserRole.viewer : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    unpublished: null;
} | {
    flagged: null;
} | {
    draft: null;
}): VideoStatus {
    return "published" in value ? VideoStatus.published : "unpublished" in value ? VideoStatus.unpublished : "flagged" in value ? VideoStatus.flagged : "draft" in value ? VideoStatus.draft : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CommentPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CommentPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    active: null;
} | {
    ended: null;
} | {
    archived: null;
}): LiveStreamStatus {
    return "scheduled" in value ? LiveStreamStatus.scheduled : "active" in value ? LiveStreamStatus.active : "ended" in value ? LiveStreamStatus.ended : "archived" in value ? LiveStreamStatus.archived : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdPublic>): Array<AdPublic> {
    return value.map((x)=>from_candid_AdPublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AdSlotType, bigint]>): Array<[AdSlotType, bigint]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoPublic>): Array<VideoPublic> {
    return value.map((x)=>from_candid_VideoPublic_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveStreamPublic>): Array<LiveStreamPublic> {
    return value.map((x)=>from_candid_LiveStreamPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreatorPayout>): Array<CreatorPayout> {
    return value.map((x)=>from_candid_CreatorPayout_n35(_uploadFile, _downloadFile, x));
}
function to_candid_AdPurchaseRequest_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPurchaseRequest): _AdPurchaseRequest {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_AdSlotType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdSlotType): _AdSlotType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterRequest_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterRequest): _RegisterRequest {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    name: string;
    targetUrl: string;
    logoUrl: string;
    slotType: AdSlotType;
}): {
    durationDays: bigint;
    name: string;
    targetUrl: string;
    logoUrl: string;
    slotType: _AdSlotType;
} {
    return {
        durationDays: value.durationDays,
        name: value.name,
        targetUrl: value.targetUrl,
        logoUrl: value.logoUrl,
        slotType: to_candid_AdSlotType_n9(_uploadFile, _downloadFile, value.slotType)
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: UserRole;
    email: string;
}): {
    username: string;
    role: _UserRole;
    email: string;
} {
    return {
        username: value.username,
        role: to_candid_UserRole_n44(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username?: string;
    email?: string;
}): {
    username: [] | [string];
    email: [] | [string];
} {
    return {
        username: value.username ? candid_some(value.username) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdSlotType): {
    homepage_banner: null;
} | {
    sidebar: null;
} | {
    pre_roll: null;
} {
    return value == AdSlotType.homepage_banner ? {
        homepage_banner: null
    } : value == AdSlotType.sidebar ? {
        sidebar: null
    } : value == AdSlotType.pre_roll ? {
        pre_roll: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    creator: null;
} | {
    admin: null;
} | {
    advertiser: null;
} | {
    viewer: null;
} {
    return value == UserRole.creator ? {
        creator: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.advertiser ? {
        advertiser: null
    } : value == UserRole.viewer ? {
        viewer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
